---
version: "3.4"
services:
  s3gw:
    image: quay.io/s3gw/s3gw:latest
    restart: always
    ports:
      - "7480:7480"
    environment:
      RGW_DEFAULT_USER_ACCESS_KEY: "test"
      RGW_DEFAULT_USER_SECRET_KEY: "test"
    volumes:
      - data:/data

  s3gw-ui:
    image: quay.io/s3gw/s3gw-ui:latest
    restart: always
    stop_signal: SIGINT
    depends_on:
      - s3gw
    ports:
      - "8080:8080"
    environment:
      S3GW_SERVICE_URL: "http://s3gw:7480"

volumes:
  data:
