IMAGE_NAME = ENV["IMAGE_NAME"] || "generic/ubuntu2004"
VM_NET = ENV["VM_NET"] || "10.46.201"
VM_NET_LAST_OCTET_START = Integer(ENV["VM_NET_LAST_OCTET_START"] || "101")
WORKER_COUNT = Integer(ENV["WORKER_COUNT"] || "1")

ansible_groups = {
  "admins" => [
    "admin"
  ],
  "workers" => [
    "worker-[1:#{WORKER_COUNT}]"
  ]
}

Vagrant.configure("2") do |config|

	config.ssh.insert_key = false
	config.vm.provider "libvirt" do |lv|
	  lv.connect_via_ssh = false
	  lv.qemu_use_session = false
	  lv.nic_model_type = "e1000"
	  lv.cpu_mode = 'host-passthrough'
	end
	
	#admin node
	config.vm.define "admin" do |admin|
		admin.vm.provider "libvirt" do |lv|
		  lv.memory = 4096
		  lv.cpus = 2
		end

        admin.vm.box = IMAGE_NAME
		admin.vm.network "private_network", autostart: true, ip: "#{VM_NET}.#{VM_NET_LAST_OCTET_START}"
        admin.vm.hostname = "admin"
    end

	#worker nodes
	(1..WORKER_COUNT).each do |i|
		config.vm.define "worker-#{i}" do |worker|
			worker.vm.provider "libvirt" do |lv|
				lv.memory = 4096
				lv.cpus = 2
				lv.storage :file, size: "5G", type: 'qcow2', serial: "674620#{i}"
			end

			worker.vm.box = IMAGE_NAME
			worker.vm.hostname = "worker-#{i}"
			worker.vm.network "private_network", autostart: true, ip: "#{VM_NET}.#{VM_NET_LAST_OCTET_START+i}"

			# Only execute once the Ansible provisioner,
			# when all the workers are up and ready.
			if i == WORKER_COUNT
				worker.vm.provision :ansible do |ansible|
					ansible.limit = "all"
					ansible.playbook = "playbooks/bootstrap.yaml"
					ansible.groups = ansible_groups
					ansible.extra_vars = {
						worker_count: WORKER_COUNT
					}
				end
				worker.vm.provision :ansible do |ansible|
					ansible.limit = "all"
					ansible.playbook = "playbooks/k8s-install.yaml"
					ansible.groups = ansible_groups
					ansible.extra_vars = {
						worker_count: WORKER_COUNT
					}
				end
			end
		end
	end

end
