#!/bin/bash
# generate-spec.sh - create spec files for a k3s cluster with longhorn and s3gw
# Copyright 2022 SUSE, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

tgtfile="s3gw.yaml"
is_dev_env=false

s3gw_pod_yaml="s3gw-pod"

while [[ $# -gt 0 ]]; do
  case $1 in
    --output|-o)
      tgtfile="${2}"
      shift 1
      ;;
    --dev)
      s3gw_pod_yaml="s3gw-pod-dev"
      ;;
  esac
  shift 1
done

[[ -z "${tgtfile}" ]] && \
  echo "error: missing output file" >&2 && \
  exit 1

specs=(
  "longhorn-ingress"
  "longhorn-s3gw-secret"
  "longhorn-storageclass"
  "s3gw-namespace"
  "s3gw-pvc"
  ${s3gw_pod_yaml}
  "s3gw-service"
  "s3gw-ingress"
)

d="$(date +'%Y/%M/%d %H:%m:%S %Z')"

cat > ${tgtfile} << EOF
# ${tgtfile} - setup a k3s cluster with longhorn and s3gw
# Copyright 2022 SUSE, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file was auto-generated by generate-spec.sh on ${d}
#

EOF

has_prior=false
for spec in ${specs[@]}; do
  ${has_prior} && echo "---" >> ${tgtfile}
  has_prior=true
  cat ${spec}.yaml >> ${tgtfile}
done
