---
name: Build S3-Tests Runner
on:
  push:
    branches:
      - "main"
    paths:
      - "tools/s3tests/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/aquarist-labs/s3tr:latest
            ghcr.io/aquarist-labs/s3tr:${{ github.sha }}
          file: 'tools/s3tests/Dockerfile'
          context: 'tools/s3tests'
